# ----------------------------------------------------------------------------
# Copyright (c) 2018-2022, QIIME 2 development team.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------
from q2dataflow.languages.wdl.util import Q2_WDL_VERSION
from q2dataflow.languages.wdl.templaters.helpers import WdlSignatureConverter
from q2dataflow.core.signature_converter.case import make_action_template_id
from q2dataflow.core.signature_converter.util import \
    get_q2_version, get_copyright


def _append_or_extend(content_holder, new_content):
    if type(new_content) is list:
        content_holder.extend(new_content)
    else:
        content_holder.append(new_content)
    return content_holder


class WdlActionTemplate:
    def __init__(self, plugin_id, action_id, template_id):
        self._plugin_id = plugin_id
        self._action_id = action_id
        self._template_id = template_id
        self._wkflow_id = f"wkflw_{self._template_id}"
        self._param_cases = []

    def add_param(self, param_case):
        self._param_cases.append(param_case)

    def _get_param_strs(self, get_inputs, include_defaults):
        param_strs = []
        for curr_param in self._param_cases:
            if get_inputs:
                curr_param_strs = curr_param.inputs(include_defaults=include_defaults)
            else:
                curr_param_strs = curr_param.outputs()
            param_strs = _append_or_extend(param_strs, curr_param_strs)

        return param_strs

    def _get_delimited_param_str(self, get_inputs, include_defaults, delimiter):
        result = ""
        param_strs = self._get_param_strs(get_inputs, include_defaults)

        if len(param_strs) > 0:
            result = delimiter.join(param_strs)

        return result

    def _get_input_declarations(self, delimiter="\n    "):
        result = self._get_delimited_param_str(True, False, delimiter)
        return result

    def _get_input_declarations_w_defaults(self, delimiter="\n        "):
        result = ""
        input_strs = self._get_delimited_param_str(True, True, delimiter)

        if input_strs:
            result = f"""input {{
        {input_strs}
    }}"""
        return result

    def _get_input_assignments(self, separator=": ", delimiter=",\n        "):
        inputs = self._get_param_strs(True, False)
        input_names_only = [x.split()[1] for x in inputs]
        input_name_pairs = [f"{x}{separator}{x}" for x in input_names_only]
        return delimiter.join(input_name_pairs)

    def _get_outputs(self, delimiter="\n        "):
        result = ""
        outputs_str = self._get_delimited_param_str(False, False, delimiter)
        if outputs_str:
            result = f"""output {{
        {outputs_str}
    }}"""
        return result

    def make_input_dict(self):
        input_dict = {}
        for curr_param in self._param_cases:
            curr_input_dict = curr_param.args()
            for k, v in curr_input_dict.items():
                # val = v if type(v) != set else list(v)
                input_dict[f"{self._wkflow_id}.{k}"] = v

        return input_dict

    def _make_task_str(self):
        task_str = f"""
version 1.0

struct {self._template_id}_params {{
    {self._get_input_declarations()}
}}

task {self._template_id} {{

    {self._get_input_declarations_w_defaults()}

    {self._template_id}_params task_params = object {{
        {self._get_input_assignments()}
    }}

    command {{
        q2dataflow q2wdl run {self._plugin_id} {self._action_id} ~{{write_json(task_params)}}
    }}

    {self._get_outputs()}

}}
"""
        return task_str

    def make_workflow_str(self):
        task_str = self._make_task_str()

        wrkflow_str = f"""
{task_str}

workflow {self._wkflow_id} {{
{self._get_input_declarations_w_defaults()}

    call {self._template_id} {{
        input: {self._get_input_assignments(separator="=", delimiter=", ")}
    }}

}}
"""

        return wrkflow_str


def make_wdl_action_template(plugin_id, action, arguments=None):
    wdl_sig_converter = WdlSignatureConverter()
    template_id = make_action_template_id(plugin_id, action.id, replace_underscores=False)
    wdl_template = WdlActionTemplate(plugin_id, action.id, template_id)

    cases = wdl_sig_converter.signature_to_param_cases(
        action.signature, arguments=arguments, include_outputs=True)
    for case in cases:
        wdl_template.add_param(case)

    return wdl_template


def make_action_template_str(settings, plugin, action):
    wdl_template = make_wdl_action_template(plugin.id, action)
    return wdl_template.make_workflow_str()


def store_action_template_str(action_template_str, filepath):
    temp_lines = []
    temp_lines.append(get_copyright())
    temp_lines.append(
        "\nThis template was automatically generated by:\n"
        f"    q2wdl (version: {Q2_WDL_VERSION})\n"
        "for:\n"
        f"    qiime2 (version: {get_q2_version()})\n")

    temp_line_str = "\n".join(temp_lines)
    commented_str = "# " + "\n# ".join(temp_line_str.split("\n"))
    output_str = "\n".join([commented_str, action_template_str])

    with open(filepath, 'w') as fh:
        fh.write(output_str)